name: Verible Linter
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: chipsalliance/verible-linter-action@main
      with:
        paths: |
          .
          ./tests
        extra_args: "--check_syntax=true"
        #github_token: ${{ secrets.GITHUB_TOKEN }}
